from pipeline import analyze_contract

# Dummy file wrapper (same as before)
class DummyFile:
    def __init__(self, path):
        self.name = path
        self.path = path

    def read(self):
        with open(self.path, "rb") as f:
            return f.read()


# Mock LLM
def mock_llm(prompt):
    return "Simple explanation generated by LLM."


file = DummyFile("data/samples/sample.txt")

result = analyze_contract(file, mock_llm)

print("\nCONTRACT TYPE:", result["contract_type"])
print("LANGUAGE:", result["language"])
print("CONTRACT RISK:", result["contract_risk"])

for c in result["clauses"]:
    print("\n-----------------------")
    print("Clause:", c["text"])
    print("Intent:", c["intent"])
    print("Risks:", c["risks"])
    print("Explanation:", c["explanation"])
